services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatsphere-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - MONGO_URI=mongodb://admin:qwerty@mongo:27017/chatsphere?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatsphere-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: chatsphere-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: chatsphere-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
